// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OfficeJukebox.Infrastructure.Persistence;

#nullable disable

namespace OfficeJukebox.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(JukeboxDbContext))]
    [Migration("20260722061135_AddTrackPlayQueuedAt")]
    partial class AddTrackPlayQueuedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AdminUsers", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.ProviderCredential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedAccessToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EncryptedRefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Scopes")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider")
                        .IsUnique();

                    b.ToTable("ProviderCredentials", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.RickRollTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RickRollTargets", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.SearchTerm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsForbidden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Term")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SearchTerms", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.SoundBoardEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AudioUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SoundBoardEvents", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Excluded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalLink")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("QueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Status", "Id");

                    b.ToTable("TrackPlays", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlayLike", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ByUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackPlayId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackPlayId");

                    b.ToTable("TrackPlayLikes", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlayVeto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ByUser")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TrackPlayId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VetoedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TrackPlayId");

                    b.ToTable("TrackPlayVetoes", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ComputedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalLink")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcluded")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MillisecondsSinceLastPlay")
                        .HasColumnType("REAL");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TrackJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "ExternalId")
                        .IsUnique();

                    b.ToTable("TrackScores", (string)null);
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlay", b =>
                {
                    b.OwnsOne("OfficeJukebox.Domain.Entities.Track", "Track", b1 =>
                        {
                            b1.Property<Guid>("TrackPlayId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("ArtistsJson")
                                .IsRequired()
                                .HasMaxLength(2048)
                                .HasColumnType("TEXT");

                            b1.Property<long>("DurationMilliseconds")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Link")
                                .IsRequired()
                                .HasMaxLength(1024)
                                .HasColumnType("TEXT");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(512)
                                .HasColumnType("TEXT");

                            b1.Property<string>("TrackArtworkUrl")
                                .HasMaxLength(1024)
                                .HasColumnType("TEXT");

                            b1.HasKey("TrackPlayId");

                            b1.ToTable("TrackPlays");

                            b1.WithOwner()
                                .HasForeignKey("TrackPlayId");

                            b1.OwnsOne("OfficeJukebox.Domain.Entities.Album", "Album", b2 =>
                                {
                                    b2.Property<Guid>("TrackPlayId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Name")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("TEXT");

                                    b2.HasKey("TrackPlayId");

                                    b2.ToTable("TrackPlays");

                                    b2.WithOwner()
                                        .HasForeignKey("TrackPlayId");
                                });

                            b1.Navigation("Album");
                        });

                    b.Navigation("Track")
                        .IsRequired();
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlayLike", b =>
                {
                    b.HasOne("OfficeJukebox.Domain.Entities.TrackPlay", "TrackPlay")
                        .WithMany("Likes")
                        .HasForeignKey("TrackPlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackPlay");
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlayVeto", b =>
                {
                    b.HasOne("OfficeJukebox.Domain.Entities.TrackPlay", "TrackPlay")
                        .WithMany("Vetoes")
                        .HasForeignKey("TrackPlayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TrackPlay");
                });

            modelBuilder.Entity("OfficeJukebox.Domain.Entities.TrackPlay", b =>
                {
                    b.Navigation("Likes");

                    b.Navigation("Vetoes");
                });
#pragma warning restore 612, 618
        }
    }
}
